// const keyboardData = [
//   {
//     id: 1,
//     name: "Corsair K70 RGB MK.2",
//     brand: "Corsair",
//     switchType: "Cherry MX Red",
//     layout: "ANSI",
//     price: 160,
//     image: "/images/keyboards/corsair-k70.jpg",
//   },
//   {
//     id: 2,
//     name: "Logitech G Pro X",
//     brand: "Logitech",
//     switchType: "GX Blue",
//     layout: "ANSI",
//     price: 150,
//     image: "/images/keyboards/logitech-gprox.jpg",
//   },
//   {
//     id: 3,
//     name: "Razer BlackWidow V3",
//     brand: "Razer",
//     switchType: "Green Mechanical",
//     layout: "ANSI",
//     price: 140,
//     image: "/images/keyboards/razer-blackwidow-v3.jpg",
//   },
//   {
//     id: 4,
//     name: "Ducky One 2 Mini",
//     brand: "Ducky",
//     switchType: "Cherry MX Brown",
//     layout: "60%",
//     price: 110,
//     image: "/images/keyboards/ducky-one2-mini.jpg",
//   },
//   {
//     id: 5,
//     name: "Keychron K6",
//     brand: "Keychron",
//     switchType: "Gateron Red",
//     layout: "65%",
//     price: 80,
//     image: "/images/keyboards/keychron-k6.jpg",
//   },
//   {
//     id: 6,
//     name: "Anne Pro 2",
//     brand: "Anne Pro",
//     switchType: "Kailh Box White",
//     layout: "60%",
//     price: 100,
//     image: "/images/keyboards/anne-pro-2.jpg",
//   },
//   {
//     id: 7,
//     name: "SteelSeries Apex Pro",
//     brand: "SteelSeries",
//     switchType: "OmniPoint Adjustable",
//     layout: "ANSI",
//     price: 200,
//     image: "/images/keyboards/steelseries-apex-pro.jpg",
//   },
//   {
//     id: 8,
//     name: "HyperX Alloy FPS Pro",
//     brand: "HyperX",
//     switchType: "Cherry MX Red",
//     layout: "Tenkeyless",
//     price: 90,
//     image: "/images/keyboards/hyperx-alloy-fps-pro.jpg",
//   },
//   {
//     id: 9,
//     name: "Varmilo VA87M",
//     brand: "Varmilo",
//     switchType: "Cherry MX Blue",
//     layout: "Tenkeyless",
//     price: 130,
//     image: "/images/keyboards/varmilo-va87m.jpg",
//   },
//   {
//     id: 10,
//     name: "Logitech MX Keys",
//     brand: "Logitech",
//     switchType: "Scissor",
//     layout: "Full-size",
//     price: 100,
//     image: "/images/keyboards/logitech-mx-keys.jpg",
//   },
// ];

// export default keyboardData;
