// const monitorData = [
//   {
//     id: 1,
//     name: "Dell UltraSharp U2723QE",
//     brand: "Dell",
//     size: "27 inch",
//     resolution: "3840x2160 (4K UHD)",
//     refreshRate: "60Hz",
//     price: 700,
//     image: "/images/monitors/dell-ultrasharp-u2723qe.jpg",
//   },
//   {
//     id: 2,
//     name: "ASUS ROG Swift PG259QN",
//     brand: "ASUS",
//     size: "24.5 inch",
//     resolution: "1920x1080 (FHD)",
//     refreshRate: "360Hz",
//     price: 700,
//     image: "/images/monitors/asus-rog-pg259qn.jpg",
//   },
//   {
//     id: 3,
//     name: "LG 34WN80C-B",
//     brand: "LG",
//     size: "34 inch",
//     resolution: "3440x1440 (WQHD)",
//     refreshRate: "60Hz",
//     price: 550,
//     image: "/images/monitors/lg-34wn80c-b.jpg",
//   },
//   {
//     id: 4,
//     name: "Samsung Odyssey G7",
//     brand: "Samsung",
//     size: "27 inch",
//     resolution: "2560x1440 (QHD)",
//     refreshRate: "240Hz",
//     price: 600,
//     image: "/images/monitors/samsung-odyssey-g7.jpg",
//   },
//   {
//     id: 5,
//     name: "Acer Predator XB273K",
//     brand: "Acer",
//     size: "27 inch",
//     resolution: "3840x2160 (4K UHD)",
//     refreshRate: "144Hz",
//     price: 800,
//     image: "/images/monitors/acer-predator-xb273k.jpg",
//   },
//   {
//     id: 6,
//     name: "BenQ EX3501R",
//     brand: "BenQ",
//     size: "35 inch",
//     resolution: "3440x1440 (WQHD)",
//     refreshRate: "100Hz",
//     price: 650,
//     image: "/images/monitors/benq-ex3501r.jpg",
//   },
//   {
//     id: 7,
//     name: "ViewSonic XG270QG",
//     brand: "ViewSonic",
//     size: "27 inch",
//     resolution: "2560x1440 (QHD)",
//     refreshRate: "165Hz",
//     price: 650,
//     image: "/images/monitors/viewsonic-xg270qg.jpg",
//   },
//   {
//     id: 8,
//     name: "Dell S3222HG",
//     brand: "Dell",
//     size: "32 inch",
//     resolution: "2560x1440 (QHD)",
//     refreshRate: "165Hz",
//     price: 450,
//     image: "/images/monitors/dell-s3222hg.jpg",
//   },
//   {
//     id: 9,
//     name: "LG 27GL850-B",
//     brand: "LG",
//     size: "27 inch",
//     resolution: "2560x1440 (QHD)",
//     refreshRate: "144Hz",
//     price: 400,
//     image: "/images/monitors/lg-27gl850-b.jpg",
//   },
//   {
//     id: 10,
//     name: "ASUS TUF Gaming VG27AQ",
//     brand: "ASUS",
//     size: "27 inch",
//     resolution: "2560x1440 (QHD)",
//     refreshRate: "165Hz",
//     price: 430,
//     image: "/images/monitors/asus-tuf-vg27aq.jpg",
//   },
// ];

// export default monitorData;
