// const mouseData = [
//   {
//     id: 1,
//     name: "Logitech G502 HERO",
//     brand: "Logitech",
//     dpi: "16000",
//     sensorType: "Optical",
//     price: 50,
//     image: "/images/mice/logitech-g502.jpg",
//   },
//   {
//     id: 2,
//     name: "Razer DeathAdder V2",
//     brand: "Razer",
//     dpi: "20000",
//     sensorType: "Optical",
//     price: 70,
//     image: "/images/mice/razer-deathadder-v2.jpg",
//   },
//   {
//     id: 3,
//     name: "Corsair Dark Core RGB Pro",
//     brand: "Corsair",
//     dpi: "18000",
//     sensorType: "Optical",
//     price: 90,
//     image: "/images/mice/corsair-dark-core.jpg",
//   },
//   {
//     id: 4,
//     name: "SteelSeries Rival 3",
//     brand: "SteelSeries",
//     dpi: "8500",
//     sensorType: "Optical",
//     price: 30,
//     image: "/images/mice/steelseries-rival-3.jpg",
//   },
//   {
//     id: 5,
//     name: "Logitech MX Master 3",
//     brand: "Logitech",
//     dpi: "4000",
//     sensorType: "Laser",
//     price: 100,
//     image: "/images/mice/logitech-mx-master-3.jpg",
//   },
//   {
//     id: 6,
//     name: "Razer Basilisk V3",
//     brand: "Razer",
//     dpi: "20000",
//     sensorType: "Optical",
//     price: 80,
//     image: "/images/mice/razer-basilisk-v3.jpg",
//   },
//   {
//     id: 7,
//     name: "Glorious Model O",
//     brand: "Glorious",
//     dpi: "12000",
//     sensorType: "Optical",
//     price: 50,
//     image: "/images/mice/glorious-model-o.jpg",
//   },
//   {
//     id: 8,
//     name: "Cooler Master MM710",
//     brand: "Cooler Master",
//     dpi: "16000",
//     sensorType: "Optical",
//     price: 40,
//     image: "/images/mice/cm-mm710.jpg",
//   },
//   {
//     id: 9,
//     name: "HyperX Pulsefire Surge",
//     brand: "HyperX",
//     dpi: "16000",
//     sensorType: "Optical",
//     price: 60,
//     image: "/images/mice/hyperx-pulsefire.jpg",
//   },
//   {
//     id: 10,
//     name: "ASUS ROG Gladius III",
//     brand: "ASUS",
//     dpi: "19000",
//     sensorType: "Optical",
//     price: 80,
//     image: "/images/mice/asus-rog-gladius.jpg",
//   },
// ];

// export default mouseData;
