const psuData = [
  {
    id: 1,
    name: "Corsair RM850x",
    brand: "Corsair",
    wattage: 850,
    certification: "80+ Gold",
    modular: "Fully Modular",
    price: 140,
    image: "/images/psu/corsair-rm850x.jpg",
  },
  {
    id: 2,
    name: "Seasonic Focus GX-750",
    brand: "Seasonic",
    wattage: 750,
    certification: "80+ Gold",
    modular: "Fully Modular",
    price: 120,
    image: "/images/psu/seasonic-gx750.jpg",
  },
  {
    id: 3,
    name: "EVGA SuperNOVA 650 G5",
    brand: "EVGA",
    wattage: 650,
    certification: "80+ Gold",
    modular: "Fully Modular",
    price: 110,
    image: "/images/psu/evga-650g5.jpg",
  },
  {
    id: 4,
    name: "Cooler Master MWE Bronze 600",
    brand: "Cooler Master",
    wattage: 600,
    certification: "80+ Bronze",
    modular: "Non-Modular",
    price: 65,
    image: "/images/psu/cm-mwe600.jpg",
  },
  {
    id: 5,
    name: "Thermaltake Smart 500W",
    brand: "Thermaltake",
    wattage: 500,
    certification: "80+ White",
    modular: "Non-Modular",
    price: 45,
    image: "/images/psu/tt-smart500w.jpg",
  },
  {
    id: 6,
    name: "Be Quiet! Straight Power 11 750W",
    brand: "Be Quiet!",
    wattage: 750,
    certification: "80+ Platinum",
    modular: "Fully Modular",
    price: 160,
    image: "/images/psu/bequiet-750w.jpg",
  },
  {
    id: 7,
    name: "ASUS ROG Strix 1000W",
    brand: "ASUS",
    wattage: 1000,
    certification: "80+ Gold",
    modular: "Fully Modular",
    price: 200,
    image: "/images/psu/asus-rog1000w.jpg",
  },
  {
    id: 8,
    name: "Antec NeoECO 550W",
    brand: "Antec",
    wattage: 550,
    certification: "80+ Bronze",
    modular: "Semi-Modular",
    price: 70,
    image: "/images/psu/antec-neoeco550.jpg",
  },
  {
    id: 9,
    name: "Gigabyte P650B",
    brand: "Gigabyte",
    wattage: 650,
    certification: "80+ Bronze",
    modular: "Non-Modular",
    price: 55,
    image: "/images/psu/gigabyte-650b.jpg",
  },
  {
    id: 10,
    name: "Corsair CX550",
    brand: "Corsair",
    wattage: 550,
    certification: "80+ Bronze",
    modular: "Semi-Modular",
    price: 60,
    image: "/images/psu/corsair-cx550.jpg",
  },
];

export default psuData;
