// const coolerData = [
//   {
//     id: 1,
//     name: "Cooler Master Hyper 212",
//     type: "Air Cooler",
//     size: "120mm",
//     price: 45,
//     image: "/images/cooler/hyper-212.jpg",
//   },
//   {
//     id: 2,
//     name: "NZXT Kraken X63",
//     type: "Liquid Cooler",
//     size: "280mm",
//     price: 150,
//     image: "/images/cooler/nzxt-kraken.jpg",
//   },
//   {
//     id: 3,
//     name: "Noctua NH-D15",
//     type: "Air Cooler",
//     size: "140mm",
//     price: 100,
//     image: "/images/cooler/noctua-nh-d15.jpg",
//   },
//   {
//     id: 4,
//     name: "Arctic Freezer 34 eSports DUO",
//     type: "Air Cooler",
//     size: "120mm",
//     price: 40,
//     image: "/images/cooler/arctic-freezer-34.jpg",
//   },
//   {
//     id: 5,
//     name: "Corsair iCUE H150i Elite Capellix",
//     type: "Liquid Cooler",
//     size: "360mm",
//     price: 180,
//     image: "/images/cooler/corsair-h150i.jpg",
//   },
//   {
//     id: 6,
//     name: "be quiet! Dark Rock Pro 4",
//     type: "Air Cooler",
//     size: "135mm",
//     price: 90,
//     image: "/images/cooler/bequiet-darkrock4.jpg",
//   },
//   {
//     id: 7,
//     name: "DeepCool GAMMAXX 400",
//     type: "Air Cooler",
//     size: "120mm",
//     price: 30,
//     image: "/images/cooler/deepcool-gammaxx400.jpg",
//   },
//   {
//     id: 8,
//     name: "EK AIO Elite 360 D-RGB",
//     type: "Liquid Cooler",
//     size: "360mm",
//     price: 210,
//     image: "/images/cooler/ek-aio-elite.jpg",
//   },
//   {
//     id: 9,
//     name: "Thermaltake TH240 ARGB",
//     type: "Liquid Cooler",
//     size: "240mm",
//     price: 110,
//     image: "/images/cooler/thermaltake-th240.jpg",
//   },
//   {
//     id: 10,
//     name: "ID-COOLING SE-224-XT",
//     type: "Air Cooler",
//     size: "120mm",
//     price: 25,
//     image: "/images/cooler/idcooling-se224xt.jpg",
//   },
//   {
//     id: 11,
//     name: "MSI MAG CORELIQUID 240R",
//     type: "Liquid Cooler",
//     size: "240mm",
//     price: 130,
//     image: "/images/cooler/msi-coreliquid-240r.jpg",
//   },
//   {
//     id: 12,
//     name: "Cooler Master ML240L RGB V2",
//     type: "Liquid Cooler",
//     size: "240mm",
//     price: 100,
//     image: "/images/cooler/cm-ml240l-v2.jpg",
//   },
// ];

// export default coolerData;
