// const cpuData = [
//   {
//     id: 1,
//     name: "Intel Core i5-13400F",
//     brand: "Intel",
//     cores: 10,
//     threads: 16,
//     baseClock: "2.5GHz",
//     boostClock: "4.6GHz",
//     socket: "LGA1700",
//     price: 220,
//     image: "/images/cpu/i5-13400f.jpg",
//   },
//   {
//     id: 2,
//     name: "Intel Core i7-13700K",
//     brand: "Intel",
//     cores: 16,
//     threads: 24,
//     baseClock: "3.4GHz",
//     boostClock: "5.4GHz",
//     socket: "LGA1700",
//     price: 390,
//     image: "/images/cpu/i7-13700k.jpg",
//   },
//   {
//     id: 3,
//     name: "AMD Ryzen 5 5600X",
//     brand: "AMD",
//     cores: 6,
//     threads: 12,
//     baseClock: "3.7GHz",
//     boostClock: "4.6GHz",
//     socket: "AM4",
//     price: 250,
//     image: "/images/cpu/ryzen-5-5600x.jpg",
//   },
//   {
//     id: 4,
//     name: "AMD Ryzen 7 5800X",
//     brand: "AMD",
//     cores: 8,
//     threads: 16,
//     baseClock: "3.8GHz",
//     boostClock: "4.7GHz",
//     socket: "AM4",
//     price: 320,
//     image: "/images/cpu/ryzen-7-5800x.jpg",
//   },
//   {
//     id: 5,
//     name: "Intel Core i9-13900K",
//     brand: "Intel",
//     cores: 24,
//     threads: 32,
//     baseClock: "3.0GHz",
//     boostClock: "5.8GHz",
//     socket: "LGA1700",
//     price: 620,
//     image: "/images/cpu/i9-13900k.jpg",
//   },
//   {
//     id: 6,
//     name: "AMD Ryzen 9 5900X",
//     brand: "AMD",
//     cores: 12,
//     threads: 24,
//     baseClock: "3.7GHz",
//     boostClock: "4.8GHz",
//     socket: "AM4",
//     price: 420,
//     image: "/images/cpu/ryzen-9-5900x.jpg",
//   },
//   {
//     id: 7,
//     name: "Intel Core i3-12100F",
//     brand: "Intel",
//     cores: 4,
//     threads: 8,
//     baseClock: "3.3GHz",
//     boostClock: "4.3GHz",
//     socket: "LGA1700",
//     price: 110,
//     image: "/images/cpu/i3-12100f.jpg",
//   },
//   {
//     id: 8,
//     name: "AMD Ryzen 3 3100",
//     brand: "AMD",
//     cores: 4,
//     threads: 8,
//     baseClock: "3.6GHz",
//     boostClock: "3.9GHz",
//     socket: "AM4",
//     price: 100,
//     image: "/images/cpu/ryzen-3-3100.jpg",
//   },
//   {
//     id: 9,
//     name: "Intel Core i5-12400F",
//     brand: "Intel",
//     cores: 6,
//     threads: 12,
//     baseClock: "2.5GHz",
//     boostClock: "4.4GHz",
//     socket: "LGA1700",
//     price: 200,
//     image: "/images/cpu/i5-12400f.jpg",
//   },
//   {
//     id: 10,
//     name: "AMD Ryzen 7 7700X",
//     brand: "AMD",
//     cores: 8,
//     threads: 16,
//     baseClock: "4.5GHz",
//     boostClock: "5.4GHz",
//     socket: "AM5",
//     price: 430,
//     image: "/images/cpu/ryzen-7-7700x.jpg",
//   },
//   {
//     id: 11,
//     name: "Intel Core i9-12900K",
//     brand: "Intel",
//     cores: 16,
//     threads: 24,
//     baseClock: "3.2GHz",
//     boostClock: "5.2GHz",
//     socket: "LGA1700",
//     price: 580,
//     image: "/images/cpu/i9-12900k.jpg",
//   },
//   {
//     id: 12,
//     name: "AMD Ryzen 9 7950X",
//     brand: "AMD",
//     cores: 16,
//     threads: 32,
//     baseClock: "4.5GHz",
//     boostClock: "5.7GHz",
//     socket: "AM5",
//     price: 700,
//     image: "/images/cpu/ryzen-9-7950x.jpg",
//   },
//   {
//     id: 13,
//     name: "Intel Core i7-12700K",
//     brand: "Intel",
//     cores: 12,
//     threads: 20,
//     baseClock: "3.6GHz",
//     boostClock: "5.0GHz",
//     socket: "LGA1700",
//     price: 350,
//     image: "/images/cpu/i7-12700k.jpg",
//   },
//   {
//     id: 14,
//     name: "AMD Ryzen 5 7600X",
//     brand: "AMD",
//     cores: 6,
//     threads: 12,
//     baseClock: "4.7GHz",
//     boostClock: "5.3GHz",
//     socket: "AM5",
//     price: 300,
//     image: "/images/cpu/ryzen-5-7600x.jpg",
//   },
//   {
//     id: 15,
//     name: "Intel Core i5-13600K",
//     brand: "Intel",
//     cores: 14,
//     threads: 20,
//     baseClock: "3.5GHz",
//     boostClock: "5.1GHz",
//     socket: "LGA1700",
//     price: 320,
//     image: "/images/cpu/i5-13600k.jpg",
//   },
//   {
//     id: 16,
//     name: "AMD Ryzen Threadripper 3990X",
//     brand: "AMD",
//     cores: 64,
//     threads: 128,
//     baseClock: "2.9GHz",
//     boostClock: "4.3GHz",
//     socket: "sTRX4",
//     price: 3990,
//     image: "/images/cpu/threadripper-3990x.jpg",
//   },
//   {
//     id: 17,
//     name: "Intel Core i9-10900K",
//     brand: "Intel",
//     cores: 10,
//     threads: 20,
//     baseClock: "3.7GHz",
//     boostClock: "5.3GHz",
//     socket: "LGA1200",
//     price: 460,
//     image: "/images/cpu/i9-10900k.jpg",
//   },
//   {
//     id: 18,
//     name: "AMD Ryzen 5 3600",
//     brand: "AMD",
//     cores: 6,
//     threads: 12,
//     baseClock: "3.6GHz",
//     boostClock: "4.2GHz",
//     socket: "AM4",
//     price: 180,
//     image: "/images/cpu/ryzen-5-3600.jpg",
//   },
//   {
//     id: 19,
//     name: "Intel Pentium Gold G6400",
//     brand: "Intel",
//     cores: 2,
//     threads: 4,
//     baseClock: "4.0GHz",
//     boostClock: "N/A",
//     socket: "LGA1200",
//     price: 70,
//     image: "/images/cpu/pentium-g6400.jpg",
//   },
//   {
//     id: 20,
//     name: "AMD Athlon 3000G",
//     brand: "AMD",
//     cores: 2,
//     threads: 4,
//     baseClock: "3.5GHz",
//     boostClock: "N/A",
//     socket: "AM4",
//     price: 60,
//     image: "/images/cpu/athlon-3000g.jpg",
//   },
// ];

// export default cpuData;
