// const gpuData = [
//   {
//     id: 1,
//     name: "NVIDIA GeForce RTX 4090",
//     brand: "NVIDIA",
//     vram: "24GB GDDR6X",
//     baseClock: "2.23GHz",
//     boostClock: "2.52GHz",
//     price: 1599,
//     image: "/images/gpu/rtx-4090.jpg",
//   },
//   {
//     id: 2,
//     name: "NVIDIA GeForce RTX 4080",
//     brand: "NVIDIA",
//     vram: "16GB GDDR6X",
//     baseClock: "2.21GHz",
//     boostClock: "2.51GHz",
//     price: 1199,
//     image: "/images/gpu/rtx-4080.jpg",
//   },
//   {
//     id: 3,
//     name: "NVIDIA GeForce RTX 4070 Ti",
//     brand: "NVIDIA",
//     vram: "12GB GDDR6X",
//     baseClock: "2.31GHz",
//     boostClock: "2.61GHz",
//     price: 799,
//     image: "/images/gpu/rtx-4070ti.jpg",
//   },
//   {
//     id: 4,
//     name: "AMD Radeon RX 7900 XTX",
//     brand: "AMD",
//     vram: "24GB GDDR6",
//     baseClock: "1.9GHz",
//     boostClock: "2.5GHz",
//     price: 999,
//     image: "/images/gpu/rx-7900xtx.jpg",
//   },
//   {
//     id: 5,
//     name: "AMD Radeon RX 6800 XT",
//     brand: "AMD",
//     vram: "16GB GDDR6",
//     baseClock: "2.0GHz",
//     boostClock: "2.25GHz",
//     price: 649,
//     image: "/images/gpu/rx-6800xt.jpg",
//   },
//   {
//     id: 6,
//     name: "NVIDIA GeForce RTX 3060",
//     brand: "NVIDIA",
//     vram: "12GB GDDR6",
//     baseClock: "1.32GHz",
//     boostClock: "1.78GHz",
//     price: 329,
//     image: "/images/gpu/rtx-3060.jpg",
//   },
//   {
//     id: 7,
//     name: "AMD Radeon RX 6600",
//     brand: "AMD",
//     vram: "8GB GDDR6",
//     baseClock: "1.6GHz",
//     boostClock: "2.5GHz",
//     price: 299,
//     image: "/images/gpu/rx-6600.jpg",
//   },
//   {
//     id: 8,
//     name: "NVIDIA GeForce GTX 1660 Super",
//     brand: "NVIDIA",
//     vram: "6GB GDDR6",
//     baseClock: "1.53GHz",
//     boostClock: "1.78GHz",
//     price: 229,
//     image: "/images/gpu/gtx-1660-super.jpg",
//   },
//   {
//     id: 9,
//     name: "AMD Radeon RX 6500 XT",
//     brand: "AMD",
//     vram: "4GB GDDR6",
//     baseClock: "2.3GHz",
//     boostClock: "2.6GHz",
//     price: 199,
//     image: "/images/gpu/rx-6500xt.jpg",
//   },
//   {
//     id: 10,
//     name: "NVIDIA GeForce RTX 2060",
//     brand: "NVIDIA",
//     vram: "6GB GDDR6",
//     baseClock: "1.36GHz",
//     boostClock: "1.68GHz",
//     price: 349,
//     image: "/images/gpu/rtx-2060.jpg",
//   },
//   // Add 10+ more if needed
// ];

// export default gpuData;
