// const motherboardData = [
//   {
//     id: 1,
//     name: "ASUS ROG Strix B550-F Gaming",
//     brand: "ASUS",
//     chipset: "B550",
//     socket: "AM4",
//     formFactor: "ATX",
//     price: 180,
//     image: "/images/motherboard/asus-b550f.jpg",
//   },
//   {
//     id: 2,
//     name: "MSI MPG Z690 Carbon WiFi",
//     brand: "MSI",
//     chipset: "Z690",
//     socket: "LGA1700",
//     formFactor: "ATX",
//     price: 290,
//     image: "/images/motherboard/msi-z690-carbon.jpg",
//   },
//   {
//     id: 3,
//     name: "Gigabyte AORUS X570 Elite",
//     brand: "Gigabyte",
//     chipset: "X570",
//     socket: "AM4",
//     formFactor: "ATX",
//     price: 200,
//     image: "/images/motherboard/gigabyte-x570.jpg",
//   },
//   {
//     id: 4,
//     name: "ASRock B460M Pro4",
//     brand: "ASRock",
//     chipset: "B460",
//     socket: "LGA1200",
//     formFactor: "Micro-ATX",
//     price: 95,
//     image: "/images/motherboard/asrock-b460m.jpg",
//   },
//   {
//     id: 5,
//     name: "ASUS Prime Z790-P",
//     brand: "ASUS",
//     chipset: "Z790",
//     socket: "LGA1700",
//     formFactor: "ATX",
//     price: 210,
//     image: "/images/motherboard/asus-z790p.jpg",
//   },
//   {
//     id: 6,
//     name: "MSI MAG B550M Mortar",
//     brand: "MSI",
//     chipset: "B550",
//     socket: "AM4",
//     formFactor: "Micro-ATX",
//     price: 135,
//     image: "/images/motherboard/msi-b550m-mortar.jpg",
//   },
//   {
//     id: 7,
//     name: "Gigabyte B660M DS3H",
//     brand: "Gigabyte",
//     chipset: "B660",
//     socket: "LGA1700",
//     formFactor: "Micro-ATX",
//     price: 120,
//     image: "/images/motherboard/gigabyte-b660m.jpg",
//   },
//   {
//     id: 8,
//     name: "ASRock X670E Taichi",
//     brand: "ASRock",
//     chipset: "X670E",
//     socket: "AM5",
//     formFactor: "ATX",
//     price: 350,
//     image: "/images/motherboard/asrock-x670e.jpg",
//   },
//   {
//     id: 9,
//     name: "Biostar B450MH",
//     brand: "Biostar",
//     chipset: "B450",
//     socket: "AM4",
//     formFactor: "Micro-ATX",
//     price: 75,
//     image: "/images/motherboard/biostar-b450mh.jpg",
//   },
//   {
//     id: 10,
//     name: "ASUS TUF Gaming Z790-Plus",
//     brand: "ASUS",
//     chipset: "Z790",
//     socket: "LGA1700",
//     formFactor: "ATX",
//     price: 240,
//     image: "/images/motherboard/asus-tuf-z790.jpg",
//   },
// ];

// export default motherboardData;
