const pcCaseData = [
  {
    id: 1,
    name: "NZXT H510",
    brand: "NZXT",
    formFactor: "ATX Mid Tower",
    price: 75,
    image: "/images/case/nzxt-h510.jpg",
  },
  {
    id: 2,
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    formFactor: "ATX Mid Tower",
    price: 95,
    image: "/images/case/corsair-4000d.jpg",
  },
  {
    id: 3,
    name: "Phanteks Eclipse P400A",
    brand: "Phanteks",
    formFactor: "ATX Mid Tower",
    price: 89,
    image: "/images/case/phanteks-p400a.jpg",
  },
  {
    id: 4,
    name: "Cooler Master MasterBox NR600",
    brand: "Cooler Master",
    formFactor: "ATX Mid Tower",
    price: 70,
    image: "/images/case/cm-nr600.jpg",
  },
  {
    id: 5,
    name: "Lian Li Lancool II Mesh",
    brand: "Lian Li",
    formFactor: "ATX Mid Tower",
    price: 100,
    image: "/images/case/lianli-lancool-ii.jpg",
  },
  {
    id: 6,
    name: "Fractal Design Meshify C",
    brand: "Fractal Design",
    formFactor: "ATX Mid Tower",
    price: 95,
    image: "/images/case/fractal-meshify-c.jpg",
  },
  {
    id: 7,
    name: "Thermaltake V200 RGB",
    brand: "Thermaltake",
    formFactor: "ATX Mid Tower",
    price: 85,
    image: "/images/case/thermaltake-v200.jpg",
  },
  {
    id: 8,
    name: "Be Quiet! Pure Base 500DX",
    brand: "Be Quiet!",
    formFactor: "ATX Mid Tower",
    price: 105,
    image: "/images/case/bequiet-500dx.jpg",
  },
  {
    id: 9,
    name: "NZXT H7 Flow",
    brand: "NZXT",
    formFactor: "ATX Mid Tower",
    price: 130,
    image: "/images/case/nzxt-h7-flow.jpg",
  },
  {
    id: 10,
    name: "Antec NX410",
    brand: "Antec",
    formFactor: "ATX Mid Tower",
    price: 65,
    image: "/images/case/antec-nx410.jpg",
  },
  {
    id: 11,
    name: "Montech X3 Mesh",
    brand: "Montech",
    formFactor: "ATX Mid Tower",
    price: 55,
    image: "/images/case/montech-x3.jpg",
  },
  {
    id: 12,
    name: "SilverStone FARA R1",
    brand: "SilverStone",
    formFactor: "ATX Mid Tower",
    price: 60,
    image: "/images/case/silverstone-fara-r1.jpg",
  },
];

export default pcCaseData;
