// const ramData = [
//   {
//     id: 1,
//     name: "Corsair Vengeance LPX 16GB",
//     brand: "Corsair",
//     size: "16GB",
//     type: "DDR4",
//     speed: "3200MHz",
//     price: 65,
//     image: "/images/ram/corsair-vengeance-16gb.jpg",
//   },
//   {
//     id: 2,
//     name: "G.Skill Trident Z RGB 32GB",
//     brand: "G.Skill",
//     size: "32GB",
//     type: "DDR4",
//     speed: "3600MHz",
//     price: 120,
//     image: "/images/ram/gskill-tridentz-32gb.jpg",
//   },
//   {
//     id: 3,
//     name: "Kingston Fury Beast 16GB",
//     brand: "Kingston",
//     size: "16GB",
//     type: "DDR5",
//     speed: "5200MHz",
//     price: 90,
//     image: "/images/ram/kingston-fury-16gb.jpg",
//   },
//   {
//     id: 4,
//     name: "TeamGroup T-Force Delta RGB 32GB",
//     brand: "TeamGroup",
//     size: "32GB",
//     type: "DDR5",
//     speed: "6000MHz",
//     price: 150,
//     image: "/images/ram/teamgroup-delta-32gb.jpg",
//   },
//   {
//     id: 5,
//     name: "Patriot Viper Steel 16GB",
//     brand: "Patriot",
//     size: "16GB",
//     type: "DDR4",
//     speed: "3000MHz",
//     price: 55,
//     image: "/images/ram/patriot-viper-16gb.jpg",
//   },
//   {
//     id: 6,
//     name: "ADATA XPG GAMMIX D30 8GB",
//     brand: "ADATA",
//     size: "8GB",
//     type: "DDR4",
//     speed: "2666MHz",
//     price: 35,
//     image: "/images/ram/xpg-gammix-8gb.jpg",
//   },
//   {
//     id: 7,
//     name: "Corsair Dominator Platinum RGB 32GB",
//     brand: "Corsair",
//     size: "32GB",
//     type: "DDR5",
//     speed: "5600MHz",
//     price: 190,
//     image: "/images/ram/corsair-dominator-32gb.jpg",
//   },
//   {
//     id: 8,
//     name: "Crucial Ballistix 16GB",
//     brand: "Crucial",
//     size: "16GB",
//     type: "DDR4",
//     speed: "3200MHz",
//     price: 60,
//     image: "/images/ram/crucial-ballistix-16gb.jpg",
//   },
//   {
//     id: 9,
//     name: "G.Skill Ripjaws V 8GB",
//     brand: "G.Skill",
//     size: "8GB",
//     type: "DDR4",
//     speed: "2400MHz",
//     price: 30,
//     image: "/images/ram/gskill-ripjaws-8gb.jpg",
//   },
//   {
//     id: 10,
//     name: "Kingston Fury Beast 32GB",
//     brand: "Kingston",
//     size: "32GB",
//     type: "DDR4",
//     speed: "3600MHz",
//     price: 110,
//     image: "/images/ram/kingston-fury-32gb.jpg",
//   },
// ];

// export default ramData;
