// const storageData = [
//   {
//     id: 1,
//     name: "Samsung 970 EVO Plus 1TB",
//     type: "SSD",
//     interface: "NVMe M.2",
//     capacity: "1TB",
//     price: 110,
//     image: "/images/storage/samsung-970-evo-plus.jpg",
//   },
//   {
//     id: 2,
//     name: "WD Blue 500GB SSD",
//     type: "SSD",
//     interface: "SATA",
//     capacity: "500GB",
//     price: 55,
//     image: "/images/storage/wd-blue-500gb.jpg",
//   },
//   {
//     id: 3,
//     name: "Seagate Barracuda 2TB",
//     type: "HDD",
//     interface: "SATA",
//     capacity: "2TB",
//     price: 60,
//     image: "/images/storage/seagate-2tb.jpg",
//   },
//   {
//     id: 4,
//     name: "Crucial MX500 1TB",
//     type: "SSD",
//     interface: "SATA",
//     capacity: "1TB",
//     price: 75,
//     image: "/images/storage/crucial-mx500-1tb.jpg",
//   },
//   {
//     id: 5,
//     name: "Kingston A2000 500GB",
//     type: "SSD",
//     interface: "NVMe M.2",
//     capacity: "500GB",
//     price: 50,
//     image: "/images/storage/kingston-a2000-500gb.jpg",
//   },
//   {
//     id: 6,
//     name: "Western Digital Black SN770 1TB",
//     type: "SSD",
//     interface: "NVMe M.2",
//     capacity: "1TB",
//     price: 95,
//     image: "/images/storage/wd-black-sn770-1tb.jpg",
//   },
//   {
//     id: 7,
//     name: "Samsung 980 500GB",
//     type: "SSD",
//     interface: "NVMe M.2",
//     capacity: "500GB",
//     price: 60,
//     image: "/images/storage/samsung-980-500gb.jpg",
//   },
//   {
//     id: 8,
//     name: "Toshiba P300 1TB",
//     type: "HDD",
//     interface: "SATA",
//     capacity: "1TB",
//     price: 45,
//     image: "/images/storage/toshiba-p300-1tb.jpg",
//   },
//   {
//     id: 9,
//     name: "Seagate FireCuda 2TB",
//     type: "HDD",
//     interface: "SATA",
//     capacity: "2TB",
//     price: 80,
//     image: "/images/storage/seagate-firecuda-2tb.jpg",
//   },
//   {
//     id: 10,
//     name: "ADATA XPG SX8200 Pro 1TB",
//     type: "SSD",
//     interface: "NVMe M.2",
//     capacity: "1TB",
//     price: 100,
//     image: "/images/storage/xpg-sx8200-1tb.jpg",
//   },
//   {
//     id: 11,
//     name: "SanDisk Ultra 3D 1TB",
//     type: "SSD",
//     interface: "SATA",
//     capacity: "1TB",
//     price: 70,
//     image: "/images/storage/sandisk-ultra-1tb.jpg",
//   },
//   {
//     id: 12,
//     name: "WD Black P10 5TB",
//     type: "HDD",
//     interface: "USB 3.2",
//     capacity: "5TB",
//     price: 110,
//     image: "/images/storage/wd-black-p10-5tb.jpg",
//   },
//   {
//     id: 13,
//     name: "Patriot Burst 240GB",
//     type: "SSD",
//     interface: "SATA",
//     capacity: "240GB",
//     price: 30,
//     image: "/images/storage/patriot-burst-240gb.jpg",
//   },
// ];

// export default storageData;
